#ifndef GUARD_REGIONMAPSEC_H
#define GUARD_REGIONMAPSEC_H

#define MAPSEC_LITTLEROOT_TOWN              0x00
#define MAPSEC_OLDALE_TOWN                  0x01
#define MAPSEC_DEWFORD_TOWN                 0x02
#define MAPSEC_LAVARIDGE_TOWN               0x03
#define MAPSEC_FALLARBOR_TOWN               0x04
#define MAPSEC_VERDANTURF_TOWN              0x05
#define MAPSEC_PACIFIDLOG_TOWN              0x06
#define MAPSEC_PETALBURG_CITY               0x07
#define MAPSEC_SLATEPORT_CITY               0x08
#define MAPSEC_MAUVILLE_CITY                0x09
#define MAPSEC_RUSTBORO_CITY                0x0A
#define MAPSEC_FORTREE_CITY                 0x0B
#define MAPSEC_LILYCOVE_CITY                0x0C
#define MAPSEC_MOSSDEEP_CITY                0x0D
#define MAPSEC_SOOTOPOLIS_CITY              0x0E
#define MAPSEC_EVER_GRANDE_CITY             0x0F
#define MAPSEC_BISMARKIA_TOWN               0x10
#define MAPSEC_ROUTE_101                    0X11
#define MAPSEC_ROUTE_102                    0X12
#define MAPSEC_ROUTE_103                    0X13
#define MAPSEC_ROUTE_104                    0X14
#define MAPSEC_ROUTE_105                    0X15
#define MAPSEC_ROUTE_106                    0X16
#define MAPSEC_ROUTE_107                    0X17
#define MAPSEC_ROUTE_108                    0X18
#define MAPSEC_ROUTE_109                    0X19
#define MAPSEC_ROUTE_110                    0X1A
#define MAPSEC_ROUTE_111                    0X1B
#define MAPSEC_ROUTE_112                    0X1C
#define MAPSEC_ROUTE_113                    0X1D
#define MAPSEC_ROUTE_114                    0X1E
#define MAPSEC_ROUTE_115                    0X1F
#define MAPSEC_ROUTE_116                    0X20
#define MAPSEC_ROUTE_117                    0X21
#define MAPSEC_ROUTE_118                    0X22
#define MAPSEC_ROUTE_119                    0X23
#define MAPSEC_ROUTE_120                    0X24
#define MAPSEC_ROUTE_121                    0X25
#define MAPSEC_ROUTE_122                    0X26
#define MAPSEC_ROUTE_123                    0X27
#define MAPSEC_ROUTE_124                    0X28
#define MAPSEC_ROUTE_125                    0X29
#define MAPSEC_ROUTE_126                    0X2A
#define MAPSEC_ROUTE_127                    0X2B
#define MAPSEC_ROUTE_128                    0X2C
#define MAPSEC_ROUTE_129                    0X2D
#define MAPSEC_ROUTE_130                    0X2E
#define MAPSEC_ROUTE_131                    0X2F
#define MAPSEC_ROUTE_132                    0X30
#define MAPSEC_ROUTE_133                    0X31
#define MAPSEC_ROUTE_134                    0X32
#define MAPSEC_UNDERWATER_124               0X33
#define MAPSEC_UNDERWATER_126               0X34
#define MAPSEC_UNDERWATER_127               0X35
#define MAPSEC_UNDERWATER_128               0X36
#define MAPSEC_UNDERWATER_SOOTOPOLIS        0X37
#define MAPSEC_GRANITE_CAVE                 0X38
#define MAPSEC_MT_CHIMNEY                   0X39
#define MAPSEC_SAFARI_ZONE                  0X3A
#define MAPSEC_BATTLE_FRONTIER              0X3B
#define MAPSEC_PETALBURG_WOODS              0X3C
#define MAPSEC_RUSTURF_TUNNEL               0X3D
#define MAPSEC_ABANDONED_SHIP               0X3E
#define MAPSEC_NEW_MAUVILLE                 0X3F
#define MAPSEC_METEOR_FALLS                 0X40
#define MAPSEC_METEOR_FALLS2                0X41
#define MAPSEC_MT_PYRE                      0X42
#define MAPSEC_AQUA_HIDEOUT_OLD             0X43
#define MAPSEC_SHOAL_CAVE                   0X44
#define MAPSEC_SEAFLOOR_CAVERN              0X45
#define MAPSEC_UNDERWATER_SEAFLOOR_CAVERN   0X46
#define MAPSEC_VICTORY_ROAD                 0X47
#define MAPSEC_MIRAGE_ISLAND                0X48
#define MAPSEC_CAVE_OF_ORIGIN               0X49
#define MAPSEC_SOUTHERN_ISLAND              0X4A
#define MAPSEC_FIERY_PATH                   0X4B
#define MAPSEC_FIERY_PATH2                  0X4C
#define MAPSEC_JAGGED_PASS                  0X4D
#define MAPSEC_JAGGED_PASS2                 0X4E
#define MAPSEC_SEALED_CHAMBER               0X4F
#define MAPSEC_UNDERWATER_SEALED_CHAMBER    0X50
#define MAPSEC_SCORCHED_SLAB                0X51
#define MAPSEC_ISLAND_CAVE                  0X52
#define MAPSEC_DESERT_RUINS                 0X53
#define MAPSEC_ANCIENT_TOMB                 0X54
#define MAPSEC_INSIDE_OF_TRUCK              0X55
#define MAPSEC_SKY_PILLAR                   0X56
#define MAPSEC_SECRET_BASE                  0X57
#define MAPSEC_DYNAMIC                      0X58
#define MAPSEC_PALLET_TOWN                  0X59
#define MAPSEC_VIRIDIAN_CITY                0X5A
#define MAPSEC_PEWTER_CITY                  0X5B
#define MAPSEC_CERULEAN_CITY                0X5C
#define MAPSEC_LAVENDER_TOWN                0X5D
#define MAPSEC_VERMILION_CITY               0X5E
#define MAPSEC_CELADON_CITY                 0X5F
#define MAPSEC_FUCHSIA_CITY                 0X60
#define MAPSEC_CINNABAR_ISLAND              0X61
#define MAPSEC_INDIGO_PLATEAU               0X62
#define MAPSEC_SAFFRON_CITY                 0X63
#define MAPSEC_ROUTE_4_POKECENTER           0X64
#define MAPSEC_ROUTE_10_POKECENTER          0X65
#define MAPSEC_ROUTE_1                      0X66
#define MAPSEC_ROUTE_2                      0X67
#define MAPSEC_ROUTE_3                      0X68
#define MAPSEC_ROUTE_4                      0X69
#define MAPSEC_ROUTE_5                      0X6A
#define MAPSEC_ROUTE_6                      0X6B
#define MAPSEC_ROUTE_7                      0X6C
#define MAPSEC_ROUTE_8                      0X6D
#define MAPSEC_ROUTE_9                      0X6E
#define MAPSEC_ROUTE_10                     0X6F
#define MAPSEC_ROUTE_11                     0X70
#define MAPSEC_ROUTE_12                     0X71
#define MAPSEC_ROUTE_13                     0X72
#define MAPSEC_ROUTE_14                     0X73
#define MAPSEC_ROUTE_15                     0X74
#define MAPSEC_ROUTE_16                     0X75
#define MAPSEC_ROUTE_17                     0X76
#define MAPSEC_ROUTE_18                     0X77
#define MAPSEC_ROUTE_19                     0X78
#define MAPSEC_ROUTE_20                     0X79
#define MAPSEC_ROUTE_21                     0X7A
#define MAPSEC_ROUTE_22                     0X7B
#define MAPSEC_ROUTE_23                     0X7C
#define MAPSEC_ROUTE_24                     0X7D
#define MAPSEC_ROUTE_25                     0X7E
#define MAPSEC_VIRIDIAN_FOREST              0X7F
#define MAPSEC_MT_MOON                      0X80
#define MAPSEC_S_S_ANNE                     0X81
#define MAPSEC_UNDERGROUND_PATH             0X82
#define MAPSEC_UNDERGROUND_PATH_2           0X83
#define MAPSEC_DIGLETTS_CAVE                0X84
#define MAPSEC_KANTO_VICTORY_ROAD           0X85
#define MAPSEC_ROCKET_HIDEOUT               0X86
#define MAPSEC_SILPH_CO                     0X87
#define MAPSEC_POKEMON_MANSION              0X88
#define MAPSEC_KANTO_SAFARI_ZONE            0X89
#define MAPSEC_POKEMON_LEAGUE               0X8A
#define MAPSEC_ROCK_TUNNEL                  0X8B
#define MAPSEC_SEAFOAM_ISLANDS              0X8C
#define MAPSEC_POKEMON_TOWER                0X8D
#define MAPSEC_CERULEAN_CAVE                0X8E
#define MAPSEC_POWER_PLANT                  0X8F
#define MAPSEC_ONE_ISLAND                   0X90
#define MAPSEC_TWO_ISLAND                   0X91
#define MAPSEC_THREE_ISLAND                 0X92
#define MAPSEC_FOUR_ISLAND                  0X93
#define MAPSEC_FIVE_ISLAND                  0X94
#define MAPSEC_SEVEN_ISLAND                 0X95
#define MAPSEC_SIX_ISLAND                   0X96
#define MAPSEC_KINDLE_ROAD                  0X97
#define MAPSEC_TREASURE_BEACH               0X98
#define MAPSEC_CAPE_BRINK                   0X99
#define MAPSEC_BOND_BRIDGE                  0X9A
#define MAPSEC_THREE_ISLE_PORT              0X9B
#define MAPSEC_SEVII_ISLE_6                 0X9C
#define MAPSEC_SEVII_ISLE_7                 0X9D
#define MAPSEC_SEVII_ISLE_8                 0X9E
#define MAPSEC_SEVII_ISLE_9                 0X9F
#define MAPSEC_RESORT_GORGEOUS              0XA0
#define MAPSEC_WATER_LABYRINTH              0XA1
#define MAPSEC_FIVE_ISLE_MEADOW             0XA2
#define MAPSEC_MEMORIAL_PILLAR              0XA3
#define MAPSEC_OUTCAST_ISLAND               0XA4
#define MAPSEC_GREEN_PATH                   0XA5
#define MAPSEC_WATER_PATH                   0XA6
#define MAPSEC_RUIN_VALLEY                  0XA7
#define MAPSEC_TRAINER_TOWER                0XA8
#define MAPSEC_CANYON_ENTRANCE              0XA9
#define MAPSEC_SEVAULT_CANYON               0XAA
#define MAPSEC_TANOBY_RUINS                 0XAB
#define MAPSEC_SEVII_ISLE_22                0XAC
#define MAPSEC_SEVII_ISLE_23                0XAD
#define MAPSEC_SEVII_ISLE_24                0XAE
#define MAPSEC_NAVEL_ROCK_FRLG              0XAF
#define MAPSEC_MT_EMBER                     0XB0
#define MAPSEC_BERRY_FOREST                 0XB1
#define MAPSEC_ICEFALL_CAVE                 0XB2
#define MAPSEC_ROCKET_WAREHOUSE             0XB3
#define MAPSEC_TRAINER_TOWER_2              0XB4
#define MAPSEC_DOTTED_HOLE                  0XB5
#define MAPSEC_LOST_CAVE                    0XB6
#define MAPSEC_PATTERN_BUSH                 0XB7
#define MAPSEC_ALTERING_CAVE_FRLG           0XB8
#define MAPSEC_TANOBY_CHAMBERS              0XB9
#define MAPSEC_THREE_ISLE_PATH              0XBA
#define MAPSEC_TANOBY_KEY                   0XBB
#define MAPSEC_BIRTH_ISLAND_FRLG            0XBC
#define MAPSEC_MONEAN_CHAMBER               0XBD
#define MAPSEC_LIPTOO_CHAMBER               0XBE
#define MAPSEC_WEEPTH_CHAMBER               0XBF
#define MAPSEC_DILFORD_CHAMBER              0XC0
#define MAPSEC_SCUFIB_CHAMBER               0XC1
#define MAPSEC_RIXY_CHAMBER                 0XC2
#define MAPSEC_VIAPOIS_CHAMBER              0XC3
#define MAPSEC_EMBER_SPA                    0XC4
#define MAPSEC_SPECIAL_AREA                 0XC5
#define MAPSEC_AQUA_HIDEOUT                 0XC6
#define MAPSEC_MAGMA_HIDEOUT                0XC7
#define MAPSEC_MIRAGE_TOWER                 0XC8
#define MAPSEC_BIRTH_ISLAND                 0XC9
#define MAPSEC_FARAWAY_ISLAND               0XCA
#define MAPSEC_ARTISAN_CAVE                 0XCB
#define MAPSEC_MARINE_CAVE                  0XCC
#define MAPSEC_UNDERWATER_MARINE_CAVE       0XCD
#define MAPSEC_TERRA_CAVE                   0XCE
#define MAPSEC_UNDERWATER_105               0XCF
#define MAPSEC_UNDERWATER_125               0XD0
#define MAPSEC_UNDERWATER_129               0XD1
#define MAPSEC_DESERT_UNDERPASS             0XD2
#define MAPSEC_ALTERING_CAVE                0XD3
#define MAPSEC_NAVEL_ROCK                   0XD4
#define MAPSEC_TRAINER_HILL                 0XD5
#define MAPSEC_NONE                         0XD6

#define METLOC_SPECIAL_EGG                  0xFD
#define METLOC_IN_GAME_TRADE                0xFE
#define METLOC_FATEFUL_ENCOUNTER            0xFF

#define KANTO_MAPSEC_START  MAPSEC_PALLET_TOWN
#define KANTO_MAPSEC_END    MAPSEC_SPECIAL_AREA
#define KANTO_MAPSEC_COUNT (KANTO_MAPSEC_END - KANTO_MAPSEC_START + 1)

#endif //GUARD_REGIONMAPSEC_H
